### My Open AI Service

networks:
  my-open-ai-network:
    external: false
    name: my-open-ai-network
    driver: bridge


services:
  # docker run -itd --name cloudflared cloudflare/cloudflared:latest tunnel --no-autoupdate run --token <CLOUDFLARE_TUNNEL_TOKEN>
  cloudflared_tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - "TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}"
    networks:
      - my-open-ai-network
    # labels:
    #   # enbale watchtower updates
    #   - "com.centurylinklabs.watchtower.enable=true"