### My Open AI Service

networks:
  ai-net:
    external: false
    name: ai-net
    driver: bridge


services:
  cloudflared_tunnel:
    image: "cloudflare/cloudflared"
    container_name: "${COMPOSE_PROJECT_NAME}.cloudflared-tunnel"
    hostname: "cf-tunnel"
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - "TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}"
    networks:
      - ai-net